config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8854
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-firebrick-booby.sh
        container: qc.acc_jumpy-corn-capuchin
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-aqua-llama.sh
        container: qc.doc_geeky-cinnamon-ant
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-wheat-octopus.sh
        container: qc.doc_squirrely-brown-orangutan
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-black-coati.sh
        container: qc.doc_zippy-green-coati
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-sapphire-rat.sh
        container: qc.lic_bluesy-sapphire-wolf
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-tomato-chinook.sh
        container: qc.met_crabby-copper-axolotl
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-coral-seahorse.sh
        container: qc.sec_sleazy-denim-toad
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-aqua-meerkat.sh
        container: qc.sty_goopy-sapphire-flounder
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cerise-hyena.sh
        container: qc.sty_flaky-ultramarine-goat
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-chestnut-raccoon.sh
        container: qc.sty_bluesy-chestnut-goose
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-copper-burmese.sh
        container: qc.uni_tasty-zucchini-gerbil
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnamon-zebra.sh
        container: qc.ver_silly-mustard-shark
timeout: 5400
