config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olive-avocet.sh
        container: qc.acc_trippy-brown-cougar
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-charcoal-anteater.sh
        container: qc.doc_fuzzy-orange-dalmatian
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-coral-kakapo.sh
        container: qc.doc_slimy-celadon-hippopotamus
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brown-affenpinscher.sh
        container: qc.doc_muggy-magnolia-eel
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-wisteria-birman.sh
        container: qc.lic_trippy-cardinal-whale
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-dandelion-gharial.sh
        container: qc.met_cranky-maroon-fish
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-purple-gorilla.sh
        container: qc.sec_tacky-harlequin-seahorse
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-green-slug.sh
        container: qc.sty_craggy-buff-eel
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ultramarine-albatross.sh
        container: qc.sty_crabby-goldenrod-whippet
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-goldenrod-walrus.sh
        container: qc.uni_scanty-burgundy-caracal
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-buff-tang.sh
        container: qc.ver_gimpy-magenta-hare
timeout: 5400
