config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-brown-audemer.sh
        container: qc.acc_slimy-cinnamon-bloodhound
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-bistre-horse.sh
        container: qc.doc_woozy-tomato-turtle
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-myrtle-mouse.sh
        container: qc.doc_crabby-malachite-capybara
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-green-chihuahua.sh
        container: qc.doc_hilly-xanthic-spitz
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-flax-wrasse.sh
        container: qc.lic_wiggy-orchid-beaver
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sangria-butterfly.sh
        container: qc.met_goopy-brass-frog
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-pumpkin-bloodhound.sh
        container: qc.sec_cloudy-taupe-ant
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-asparagus-opossum.sh
        container: qc.sty_droopy-ochre-gerbil
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-white-audemer.sh
        container: qc.sty_pretty-persimmon-wolf
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-carmine-cichlid.sh
        container: qc.uni_bumpy-celadon-newfoundland
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-heliotrope-gecko.sh
        container: qc.ver_thirsty-khaki-bobcat
timeout: 5400
