config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8852
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-scarlet-heron.sh
        container: qc.acc_silly-chartreuse-mouse
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-white-zebu.sh
        container: qc.doc_randy-aquamarine-tamarin
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cerulean-fish.sh
        container: qc.doc_slaphappy-amethyst-jackal
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-denim-lionfish.sh
        container: qc.doc_skanky-flax-walrus
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-olivine-dolphin.sh
        container: qc.lic_lanky-teal-dog
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bronze-eleuth.sh
        container: qc.met_gummy-magenta-weasel
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-sangria-cheetah.sh
        container: qc.sec_crappy-champagne-seal
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-bistre-ostrich.sh
        container: qc.sty_paltry-cream-hare
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-flax-heron.sh
        container: qc.sty_snoopy-magenta-fossa
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-aqua-tortoise.sh
        container: qc.sty_bumpy-sapphire-mouse
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-dandelion-bongo.sh
        container: qc.uni_chummy-blue-bat
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-heliotrope-ray.sh
        container: qc.ver_frumpy-denim-avocet
timeout: 5400
