config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-magnolia-rattlesnake.sh
        container: qc.acc_woozy-mustard-wrasse
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-purple-cockroach.sh
        container: qc.doc_droopy-heliotrope-crane
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-salmon-impala.sh
        container: qc.doc_freaky-silver-collie
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cardinal-hedgehog.sh
        container: qc.doc_trippy-goldenrod-ferret
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-dunker.sh
        container: qc.lic_greasy-peach-skunk
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-olivine-squirrel.sh
        container: qc.met_snoopy-dandelion-devil
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-white-moorhen.sh
        container: qc.sec_blurry-chartreuse-kiwi
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-crimson-crab.sh
        container: qc.sty_pretty-aqua-dolphin
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-olive-cattle.sh
        container: qc.sty_flabby-cobalt-chow
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-harlequin-walrus.sh
        container: qc.uni_snappy-fuchsia-kiwi
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-olive-dachsbracke.sh
        container: qc.ver_stealthy-blue-barnacle
timeout: 5400
