config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-magnolia-bobcat.sh
        container: qc.acc_frumpy-magnolia-dhole
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-olivine-lion.sh
        container: qc.doc_sleepy-blue-rabbit
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-red-spoonbill.sh
        container: qc.doc_sleepy-beige-dragonfly
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-dandelion-kangaroo.sh
        container: qc.doc_hilly-lemon-dog
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cinnamon-bulldog.sh
        container: qc.lic_breezy-malachite-raccoon
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-mastiff.sh
        container: qc.met_snoopy-buff-zorse
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-bistre-moorhen.sh
        container: qc.sec_lousy-azure-chinchilla
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-wisteria-mastiff.sh
        container: qc.sty_ugly-carmine-wallaby
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-fuchsia-horse.sh
        container: qc.sty_flabby-chartreuse-slug
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-champagne-bear.sh
        container: qc.uni_stealthy-vermilion-wildebeest
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-wheat-affenpinscher.sh
        container: qc.ver_crabby-buff-spoonbill
timeout: 5400
