config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-teal-barracuda.sh
        container: qc.acc_whiny-yellow-iguana
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-gold-flounder.sh
        container: qc.doc_shabby-mauve-kakapo
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-goldenrod-urchin.sh
        container: qc.doc_sleepy-gamboge-bonobo
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-smalt-tapir.sh
        container: qc.doc_nerdy-xanthic-alligator
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-coral-tamarin.sh
        container: qc.lic_ready-amber-tzu
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-sapphire-maltese.sh
        container: qc.met_freaky-cerulean-baboon
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-apricot-bulldog.sh
        container: qc.sec_shaky-aquamarine-uguisu
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-firebrick-eleuth.sh
        container: qc.sty_greasy-tomato-jackal
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amaranth-bulldog.sh
        container: qc.sty_woozy-linen-rottweiler
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-grey-schnauzer.sh
        container: qc.uni_ugly-ultramarine-rabbit
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cinnabar-sponge.sh
        container: qc.ver_lumpy-mauve-fousek
timeout: 5400
