config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-bronze-lizard.sh
        container: qc.acc_sleepy-ruby-tetra
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brass-armadillo.sh
        container: qc.doc_grumpy-cinnabar-okapi
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olive-schnauzer.sh
        container: qc.doc_gloppy-persimmon-ocelot
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-orchid-shrew.sh
        container: qc.doc_nerdy-fuchsia-civet
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amethyst-fossa.sh
        container: qc.lic_crabby-platinum-discus
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-flax-kiwi.sh
        container: qc.met_snippy-white-corgi
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-violet-sheep.sh
        container: qc.sec_silly-champagne-camel
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-alizarin-mandrill.sh
        container: qc.sty_snazzy-peach-sparrow
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-coyote.sh
        container: qc.sty_lovely-charcoal-fox
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-plum-dragonfly.sh
        container: qc.uni_cheeky-cerulean-forest
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-brass-hummingbird.sh
        container: qc.ver_pokey-copper-markhor
timeout: 5400
