config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8857
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-emerald-snake.sh
        container: qc.acc_sloppy-brown-drever
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-champagne-caiman.sh
        container: qc.doc_muggy-saffron-skunk
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-amethyst-husky.sh
        container: qc.doc_shaky-gold-budgerigar
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-buff-caiman.sh
        container: qc.doc_woolly-periwinkle-angelfish
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-alizarin-jackal.sh
        container: qc.lic_sleepy-asparagus-dragonfly
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-viridian-terrier.sh
        container: qc.met_cranky-olivine-jellyfish
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-myrtle-coyote.sh
        container: qc.sec_breezy-magenta-quail
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-fuchsia-wombat.sh
        container: qc.sty_goopy-ultramarine-fossa
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-rust-robin.sh
        container: qc.sty_chewy-mustard-camel
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-amaranth-worm.sh
        container: qc.sty_pasty-ruby-rhinoceros
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-champagne-bonobo.sh
        container: qc.uni_woolly-blue-kangaroo
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-coral-dogfish.sh
        container: qc.ver_chewy-wheat-mule
timeout: 5400
