config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-olive-mule.sh
        container: qc.acc_blurry-azure-ibis
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-apricot-sheep.sh
        container: qc.doc_pretty-beige-crane
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-seashell-slug.sh
        container: qc.doc_sloppy-scarlet-eel
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-champagne-spoonbill.sh
        container: qc.doc_crabby-yellow-chicken
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-aquamarine-woodlouse.sh
        container: qc.lic_sleepy-zucchini-millipede
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-carmine-binturong.sh
        container: qc.met_goopy-asparagus-cat
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-dandelion-bordeaux.sh
        container: qc.sec_whiny-cerise-warthog
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-champagne-koala.sh
        container: qc.sty_craggy-chartreuse-rhinoceros
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-corn-bullfrog.sh
        container: qc.sty_homey-orchid-snake
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-lavender-salamander.sh
        container: qc.uni_craggy-heliotrope-dachsbracke
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amber-dugong.sh
        container: qc.ver_flabby-copper-bracke
timeout: 5400
