config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-peach-tzu.sh
        container: qc.acc_woozy-russet-rattlesnake
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-amber-fousek.sh
        container: qc.doc_jumpy-viridian-lionfish
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-linen-chimpanzee.sh
        container: qc.doc_skimpy-green-jackal
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cornflower-dragon.sh
        container: qc.doc_zippy-xanthic-kingfisher
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ruby-butterfly.sh
        container: qc.lic_droopy-rust-greyhound
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-tangerine-ray.sh
        container: qc.met_ready-zucchini-dragon
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-thistle-coati.sh
        container: qc.sec_wimpy-chocolate-sheep
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-olivine-chinchilla.sh
        container: qc.sty_greasy-beige-frigatebird
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-ivory-burmese.sh
        container: qc.sty_pretty-blue-sparrow
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-teal-tamarin.sh
        container: qc.uni_shabby-aquamarine-quail
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-ultramarine-newfoundland.sh
        container: qc.ver_snoopy-aquamarine-panda
timeout: 5400
