config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chartreuse-frise.sh
        container: qc.acc_nerdy-viridian-wolf
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cyan-dolphin.sh
        container: qc.doc_bumpy-lilac-squirt
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-indigo-spaniel.sh
        container: qc.doc_squirrely-thistle-guppy
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-grey-retriever.sh
        container: qc.doc_lumpy-plum-dogfish
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-zucchini-koala.sh
        container: qc.lic_frumpy-myrtle-seahorse
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-chocolate-shark.sh
        container: qc.met_greasy-razzmatazz-lemur
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-firebrick-badger.sh
        container: qc.sec_queasy-charcoal-horse
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-black-booby.sh
        container: qc.sty_sunny-magenta-shrimp
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-lilac-avocet.sh
        container: qc.sty_snoopy-cornflower-wallaby
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ivory-macaque.sh
        container: qc.uni_lanky-black-fowl
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cinnamon-gharial.sh
        container: qc.ver_scaly-heliotrope-hummingbird
timeout: 5400
