config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-taupe-wrasse.sh
        container: qc.acc_beady-cardinal-ibis
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-chestnut-echidna.sh
        container: qc.doc_dorky-lemon-mandrill
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lemon-leopard.sh
        container: qc.doc_muzzy-black-booby
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-carmine-opossum.sh
        container: qc.doc_skanky-ochre-cuttlefish
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-amethyst-monster.sh
        container: qc.lic_stuffy-thistle-wombat
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-maroon-russel.sh
        container: qc.met_pretty-asparagus-tapir
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-saffron-axolotl.sh
        container: qc.sec_lumpy-xanthic-baboon
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-chocolate-mouse.sh
        container: qc.sty_thirsty-celadon-macaque
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-ecru-angelfish.sh
        container: qc.sty_wimpy-fuchsia-ragdoll
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-yellow-reindeer.sh
        container: qc.uni_cloudy-yellow-scorpion
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-orange-scorpion.sh
        container: qc.ver_skanky-harlequin-indri
timeout: 5400
