config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8859
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-lime-echidna.sh
        container: qc.acc_slimy-beige-bonobo
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-scarlet-caterpillar.sh
        container: qc.doc_frumpy-scarlet-fossa
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-millipede.sh
        container: qc.doc_greasy-red-drever
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ivory-magpie.sh
        container: qc.doc_slaphappy-harlequin-terrier
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-chocolate-akbash.sh
        container: qc.lic_shaggy-chartreuse-gecko
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-olivine-urchin.sh
        container: qc.met_greasy-malachite-slug
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wheat-spoonbill.sh
        container: qc.sec_gummy-taupe-cheetah
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lavender-gopher.sh
        container: qc.sty_muzzy-olive-spaniel
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-smalt-hedgehog.sh
        container: qc.sty_stuffy-ochre-iguana
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-malachite-burmese.sh
        container: qc.sty_hasty-taupe-eel
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-razzmatazz-tarantula.sh
        container: qc.uni_chummy-alizarin-rabbit
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-sapphire-robin.sh
        container: qc.ver_snappy-yellow-molly
timeout: 5400
