config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-crimson-boar.sh
        container: qc.acc_lovely-sangria-olm
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-azure-bracke.sh
        container: qc.doc_tacky-vermilion-horse
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-sangria-ladybird.sh
        container: qc.doc_cloudy-thistle-wasp
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-tangerine-bombay.sh
        container: qc.doc_seedy-viridian-forest
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-myrtle-bonobo.sh
        container: qc.lic_blurry-buff-warthog
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-beige-dollar.sh
        container: qc.met_blurry-lavender-mongoose
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-beige-kiwi.sh
        container: qc.sec_hasty-tomato-scorpion
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-razzmatazz-shrimp.sh
        container: qc.sty_messy-red-horse
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cobalt-yak.sh
        container: qc.sty_sloppy-sepia-chinook
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-vermilion-bandicoot.sh
        container: qc.uni_nerdy-wisteria-capuchin
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-tangerine-jaguar.sh
        container: qc.ver_baggy-khaki-labradoodle
timeout: 5400
