config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8853
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-amethyst-mastiff.sh
        container: qc.acc_squeaky-teal-tetra
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lime-walrus.sh
        container: qc.doc_cozy-mustard-quetzal
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-grey-reindeer.sh
        container: qc.doc_paltry-ochre-bongo
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-denim-fish.sh
        container: qc.doc_silly-black-gar
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-aqua-devil.sh
        container: qc.lic_trippy-peach-mist
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-amber-barb.sh
        container: qc.met_ready-bistre-chicken
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-indigo-lemming.sh
        container: qc.sec_squirrely-azure-pinscher
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-pink-indri.sh
        container: qc.sty_bluesy-rust-chamois
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ruby-snail.sh
        container: qc.sty_flabby-pink-eagle
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ivory-tzu.sh
        container: qc.sty_homely-orange-dragon
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-flax-hyena.sh
        container: qc.uni_muzzy-olive-neanderthal
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lime-maltese.sh
        container: qc.ver_lovely-periwinkle-kangaroo
timeout: 5400
