config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-firebrick-devil.sh
        container: qc.acc_jumpy-cobalt-dingo
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-emerald-booby.sh
        container: qc.doc_tasty-olive-tarantula
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-carmine-slug.sh
        container: qc.doc_whiny-coral-earwig
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-gamboge-binturong.sh
        container: qc.doc_craggy-ruby-squirrel
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-silver-jaguar.sh
        container: qc.lic_tasty-tan-otter
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-rose-robin.sh
        container: qc.met_craggy-cobalt-bee
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-denim-kingfisher.sh
        container: qc.sec_frumpy-scarlet-fousek
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-aqua-warthog.sh
        container: qc.sty_snippy-cinnamon-foxhound
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-bronze-mole.sh
        container: qc.sty_lumpy-mustard-dachshund
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pear-terrier.sh
        container: qc.uni_lovely-amaranth-kingfisher
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-violet-shrimp.sh
        container: qc.ver_stinky-cream-javanese
timeout: 5400
