config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-crimson-labradoodle.sh
        container: qc.acc_ugly-aqua-armadillo
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cream-eel.sh
        container: qc.doc_cloudy-charcoal-kiwi
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-burgundy-discus.sh
        container: qc.doc_queasy-wisteria-budgerigar
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-saffron-javanese.sh
        container: qc.doc_stuffy-lime-dane
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-plum-kangaroo.sh
        container: qc.lic_tasty-firebrick-horse
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cinnamon-snake.sh
        container: qc.met_skimpy-ruby-gecko
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-denim-armadillo.sh
        container: qc.sec_cheeky-lemon-chipmunk
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-chocolate-birman.sh
        container: qc.sty_lovely-yellow-dalmatian
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sangria-crane.sh
        container: qc.sty_crappy-azure-wolfhound
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-red-lionfish.sh
        container: qc.uni_ready-orchid-wallaby
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-corn-quoll.sh
        container: qc.ver_stealthy-periwinkle-bullfrog
timeout: 5400
