config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8855
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cornflower-antelope.sh
        container: qc.acc_tacky-ultramarine-terrier
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-linen-goat.sh
        container: qc.doc_snappy-cream-macaw
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-asparagus-argentino.sh
        container: qc.doc_sloppy-saffron-spider
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cinnabar-buzzard.sh
        container: qc.doc_surly-peach-octopus
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lilac-bulldog.sh
        container: qc.lic_hazy-magenta-zonkey
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-mauve-bat.sh
        container: qc.met_breezy-brass-dolphin
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-brown-argentino.sh
        container: qc.sec_crabby-malachite-kiwi
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-rust-gorilla.sh
        container: qc.sty_seedy-pumpkin-zonkey
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-olive-eleuth.sh
        container: qc.sty_crabby-indigo-lion
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-firebrick-capuchin.sh
        container: qc.sty_wheezy-salmon-hare
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-goldenrod-tapir.sh
        container: qc.uni_snazzy-peach-hare
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-lime-skunk.sh
        container: qc.ver_woolly-olive-newt
timeout: 5400
