config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-azure-schnauzer.sh
        container: qc.acc_snazzy-rust-tuatara
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-wisteria-frog.sh
        container: qc.doc_boozy-pumpkin-tetra
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-thistle-walrus.sh
        container: qc.doc_lovely-amber-gerbil
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-champagne-weasel.sh
        container: qc.doc_freaky-turquoise-tzu
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-champagne-markhor.sh
        container: qc.lic_trippy-dandelion-beetle
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-amber-whale.sh
        container: qc.met_flimsy-aquamarine-ragdoll
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-bistre-balinese.sh
        container: qc.sec_homely-cerulean-hound
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cyan-alligator.sh
        container: qc.sty_lousy-persimmon-giraffe
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-mustard-ibis.sh
        container: qc.sty_wiggy-magenta-shark
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-scarlet-fossa.sh
        container: qc.uni_squeaky-ecru-coyote
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-heliotrope-binturong.sh
        container: qc.ver_squeaky-harlequin-crocodile
timeout: 5400
