config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-turquoise-dragon.sh
        container: qc.acc_stealthy-smalt-fousek
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-smalt-ant.sh
        container: qc.doc_gummy-persimmon-dachshund
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-aqua-dodo.sh
        container: qc.doc_snippy-puce-rattlesnake
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cornflower-cheetah.sh
        container: qc.doc_thirsty-russet-hyrax
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-azure-frise.sh
        container: qc.lic_woozy-lilac-mouse
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-violet-bear.sh
        container: qc.met_homely-harlequin-russel
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-seashell-insect.sh
        container: qc.sec_shaggy-maroon-spoonbill
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-tangerine-panda.sh
        container: qc.sty_homely-bistre-butterfly
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-yellow-jellyfish.sh
        container: qc.sty_flimsy-tan-otter
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-white-woodpecker.sh
        container: qc.uni_stinky-mauve-quokka
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-champagne-kingfisher.sh
        container: qc.ver_goopy-yellow-urchin
timeout: 5400
