config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bronze-neanderthal.sh
        container: qc.acc_cozy-emerald-spider
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-puce-gopher.sh
        container: qc.doc_woolly-scarlet-lemur
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-magenta-earwig.sh
        container: qc.doc_hasty-dandelion-alligator
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-taupe-mandrill.sh
        container: qc.doc_squirrely-buff-chinook
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cream-macaw.sh
        container: qc.lic_sleazy-beige-dachsbracke
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sapphire-sheepdog.sh
        container: qc.met_hilly-emerald-chinook
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-thistle-opossum.sh
        container: qc.sec_crabby-sepia-mole
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-dandelion-bloodhound.sh
        container: qc.sty_flabby-aqua-bison
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-burgundy-ladybird.sh
        container: qc.sty_goopy-chocolate-cassowary
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-malachite-reindeer.sh
        container: qc.uni_beady-goldenrod-alligator
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-malachite-heron.sh
        container: qc.ver_droopy-ultramarine-echidna
timeout: 5400
