config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cornflower-frise.sh
        container: qc.acc_thirsty-bistre-toad
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amber-harrier.sh
        container: qc.doc_shaggy-malachite-termite
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-lavender-dugong.sh
        container: qc.doc_droopy-cerulean-cattle
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-charcoal-axolotl.sh
        container: qc.doc_sleazy-cobalt-whippet
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-purple-catfish.sh
        container: qc.lic_muzzy-tomato-blue
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-amber-warthog.sh
        container: qc.met_skimpy-malachite-wolverine
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-celadon-squirt.sh
        container: qc.sec_scummy-russet-cockroach
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-wheat-audemer.sh
        container: qc.sty_tacky-zucchini-flamingo
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-brown-antelope.sh
        container: qc.sty_scummy-charcoal-dingo
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-goldenrod-wallaby.sh
        container: qc.uni_foggy-aquamarine-wolverine
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-chocolate-oyster.sh
        container: qc.ver_seedy-peach-greyhound
timeout: 5400
