config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8849
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tangerine-ostrich.sh
        container: qc.acc_chewy-dandelion-cattle
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-sapphire-argentino.sh
        container: qc.doc_cranky-amethyst-tapir
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-champagne-cattle.sh
        container: qc.doc_squirrely-peach-chihuahua
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chocolate-argentino.sh
        container: qc.doc_blurry-harlequin-scorpion
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-flax-maltese.sh
        container: qc.lic_snazzy-vermilion-beagle
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-khaki-kakapo.sh
        container: qc.met_crabby-indigo-akbash
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chartreuse-urchin.sh
        container: qc.sec_freaky-heliotrope-bordeaux
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-apricot-chinook.sh
        container: qc.sty_flimsy-orange-mongoose
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-red-tamarin.sh
        container: qc.sty_skinny-silver-flounder
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-tangerine-owl.sh
        container: qc.sty_dorky-yellow-reindeer
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cornflower-hornet.sh
        container: qc.uni_cozy-cardinal-cockroach
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-aqua-markhor.sh
        container: qc.ver_flabby-celadon-guppy
timeout: 5400
