config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cornflower-budgerigar.sh
        container: qc.acc_clammy-beige-whippet
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-vermilion-hound.sh
        container: qc.doc_zippy-magenta-terrier
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-champagne-grasshopper.sh
        container: qc.doc_flabby-carmine-cattle
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-thistle-chinook.sh
        container: qc.doc_wheezy-eggplant-jellyfish
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-tangerine-anteater.sh
        container: qc.lic_homey-goldenrod-chihuahua
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-auburn-tarsier.sh
        container: qc.met_lanky-smalt-zonkey
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-silver-wolf.sh
        container: qc.sec_messy-lilac-wombat
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-plum-retriever.sh
        container: qc.sty_flimsy-apricot-ferret
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-mauve-rhinoceros.sh
        container: qc.sty_crabby-linen-jellyfish
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sapphire-chameleon.sh
        container: qc.uni_messy-russet-tarantula
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cornflower-kiwi.sh
        container: qc.ver_grumpy-olive-civet
timeout: 5400
