config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-burgundy-stoat.sh
        container: qc.acc_shaky-pink-mau
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-chestnut-elephant.sh
        container: qc.doc_stealthy-chestnut-goose
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-ultramarine-fowl.sh
        container: qc.doc_slaphappy-myrtle-gibbon
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-malachite-boar.sh
        container: qc.doc_wimpy-gold-koala
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-sapphire-quetzal.sh
        container: qc.lic_cloudy-purple-monster
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-azure-kakapo.sh
        container: qc.met_trippy-auburn-civet
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-lime-bordeaux.sh
        container: qc.sec_bumpy-peach-frise
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-gold-capuchin.sh
        container: qc.sty_chummy-ultramarine-newt
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tomato-gecko.sh
        container: qc.sty_pretty-razzmatazz-birman
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-flax-hippopotamus.sh
        container: qc.uni_snippy-khaki-monkey
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lavender-mammoth.sh
        container: qc.ver_paltry-lime-coyote
timeout: 5400
