config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-azure-mayfly.sh
        container: qc.acc_muzzy-puce-bulldog
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-white-shrimp.sh
        container: qc.doc_tacky-cream-affenpinscher
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-buff-eel.sh
        container: qc.doc_snazzy-aquamarine-capuchin
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-bistre-rhinoceros.sh
        container: qc.doc_sunny-myrtle-cat
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ochre-dormouse.sh
        container: qc.lic_stinky-black-woodpecker
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-periwinkle-hummingbird.sh
        container: qc.met_goopy-platinum-lionfish
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-mustard-swan.sh
        container: qc.sec_hilly-goldenrod-jellyfish
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ivory-chicken.sh
        container: qc.sty_crabby-ecru-gharial
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-salmon-fowl.sh
        container: qc.sty_freaky-chestnut-swan
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-heliotrope-lemming.sh
        container: qc.uni_breezy-zucchini-hummingbird
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-puce-flamingo.sh
        container: qc.ver_breezy-ultramarine-spitz
timeout: 5400
