config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chestnut-cat.sh
        container: qc.acc_scaly-carmine-blue
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-platinum-collie.sh
        container: qc.doc_dorky-chocolate-rattlesnake
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-thistle-caracal.sh
        container: qc.doc_trippy-chestnut-vulture
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-turquoise-coati.sh
        container: qc.doc_freaky-yellow-urchin
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-asparagus-cockroach.sh
        container: qc.lic_zippy-burgundy-orangutan
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-orchid-husky.sh
        container: qc.met_shaky-linen-okapi
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lilac-lionfish.sh
        container: qc.sec_seedy-aquamarine-bongo
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sapphire-setter.sh
        container: qc.sty_chummy-russet-squid
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-aqua-dog.sh
        container: qc.sty_chummy-gamboge-tarantula
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chocolate-fly.sh
        container: qc.uni_freaky-celadon-harrier
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-bronze-hornet.sh
        container: qc.ver_wheezy-xanthic-gecko
timeout: 5400
