config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: report-8860
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-beaver.sh
        container: qc.acc_scummy-ultramarine-turkey
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnamon-fox.sh
        container: qc.doc_fuzzy-indigo-opossum
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-silver-millipede.sh
        container: qc.doc_whiny-emerald-reindeer
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-harlequin-wolfhound.sh
        container: qc.doc_greasy-jade-catfish
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-harlequin-tapir.sh
        container: qc.lic_stinky-cardinal-mastiff
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-buff-drever.sh
        container: qc.met_lovely-red-llama
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ecru-ibis.sh
        container: qc.sec_gamy-asparagus-lynx
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cardinal-rabbit.sh
        container: qc.sty_grumpy-mauve-javanese
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-heliotrope-audemer.sh
        container: qc.sty_shaggy-cerulean-angelfish
      gitlab.a.incd.pt/jprm/webinar-demo-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-gamboge-catfish.sh
        container: qc.sty_baggy-mauve-dolphin
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cerise-okapi.sh
        container: qc.uni_zippy-puce-frigatebird
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-teal-eleuth.sh
        container: qc.ver_scummy-champagne-hound
timeout: 5400
