config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-red-coyote.sh
        container: qc.acc_snappy-harlequin-dolphin
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-taupe-monster.sh
        container: qc.doc_crappy-chestnut-kiwi
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-aqua-fox.sh
        container: qc.doc_flimsy-harlequin-chicken
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-eggplant-schnauzer.sh
        container: qc.doc_chummy-platinum-orangutan
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cerulean-foxhound.sh
        container: qc.lic_pretty-chestnut-newt
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-viridian-robin.sh
        container: qc.met_freaky-tan-caiman
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tomato-lionfish.sh
        container: qc.sec_hilly-thistle-chinchilla
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tan-jaguar.sh
        container: qc.sty_flabby-lemon-budgerigar
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-red-barnacle.sh
        container: qc.sty_snazzy-olivine-tiger
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cinnamon-blue.sh
        container: qc.uni_slaphappy-chocolate-scorpion
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-woodpecker.sh
        container: qc.ver_randy-magenta-reindeer
timeout: 5400
