config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-olivine-quokka.sh
        container: qc.acc_stuffy-teal-chipmunk
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-dandelion-dragonfly.sh
        container: qc.doc_shaky-mauve-deer
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-turquoise-devil.sh
        container: qc.doc_snoopy-mauve-tamarin
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lavender-scorpion.sh
        container: qc.doc_whiny-persimmon-kingfisher
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cerise-bear.sh
        container: qc.lic_flabby-green-ragdoll
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-malachite-hornet.sh
        container: qc.met_jumpy-maroon-kakapo
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-chestnut-whale.sh
        container: qc.sec_muggy-lavender-maltese
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-vermilion-kakapo.sh
        container: qc.sty_cloudy-brass-corgi
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-heliotrope-drever.sh
        container: qc.sty_bluesy-pumpkin-swan
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-charcoal-molly.sh
        container: qc.uni_cloudy-mustard-woodpecker
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-turquoise-wolverine.sh
        container: qc.ver_sloppy-fuchsia-kangaroo
timeout: 5400
