config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-indigo-kangaroo.sh
        container: qc.acc_jumpy-sepia-squirt
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-charcoal-chamois.sh
        container: qc.doc_slaphappy-khaki-walrus
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ecru-malamute.sh
        container: qc.doc_scanty-yellow-capuchin
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-smalt-mongrel.sh
        container: qc.doc_pasty-celadon-cheetah
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ecru-serval.sh
        container: qc.lic_slimy-thistle-shrimp
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ready-linen-bat.sh
        container: qc.met_cheeky-aquamarine-octopus
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-coral-lionfish.sh
        container: qc.sec_boozy-cardinal-dodo
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-khaki-devil.sh
        container: qc.sty_queasy-sangria-tang
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-malachite-stoat.sh
        container: qc.sty_foggy-heliotrope-goose
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ochre-rhinoceros.sh
        container: qc.uni_nippy-cinnamon-nightingale
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-magenta-mule.sh
        container: qc.ver_muggy-seashell-newfoundland
timeout: 5400
