config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/webinar-demo-project:
      branch: main
      repo: https://gitlab.a.incd.pt/jprm/webinar-demo-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-peach-wolverine.sh
        container: qc.acc_sleazy-violet-buzzard
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-rust-mongoose.sh
        container: qc.doc_sleepy-pumpkin-cow
      gitlab.a.incd.pt/jprm/webinar-demo-project git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-wisteria-lionfish.sh
        container: qc.doc_skinny-black-bombay
      gitlab.a.incd.pt/jprm/webinar-demo-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-rose-snail.sh
        container: qc.doc_squeaky-cinnabar-gibbon
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-blue-hound.sh
        container: qc.lic_lovely-smalt-newfoundland
  QC.Met:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-russet-chimpanzee.sh
        container: qc.met_skimpy-rose-lemming
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-aqua-schnauzer.sh
        container: qc.sec_bluesy-orange-budgerigar
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-vermilion-spaniel.sh
        container: qc.sty_pokey-salmon-setter
      gitlab.a.incd.pt/jprm/webinar-demo-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-khaki-wolfhound.sh
        container: qc.sty_droopy-dandelion-monster
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-ivory-falcon.sh
        container: qc.uni_goopy-orange-gar
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/webinar-demo-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bistre-harrier.sh
        container: qc.ver_pretty-seashell-beagle
timeout: 5400
